import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Somnio',
  description: 'Terms of Service for Somnio (daily-dream.ai). Read our acceptable use policy, AI output disclaimer, and governing law.',
  robots: { index: true, follow: true },
};

const LAST_UPDATED = 'June 10, 2026';

export default function TermsPage() {
  return (
    <main className="min-h-screen py-24 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="mb-10">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent mb-2">
            Terms of Service
          </h1>
          <p className="text-gray-400 text-sm">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-8 text-gray-300 leading-relaxed">
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <p>
              These Terms of Service (&quot;Terms&quot;) govern your access to and use of Somnio,
              operated by <strong>Farallone Media LLC</strong> at <strong>daily-dreams.ai</strong>{' '}
              (&quot;we&quot;, &quot;us&quot;, or &quot;Somnio&quot;). By creating an account or
              using the service, you agree to these Terms. If you do not agree, do not use the
              service.
            </p>
          </section>

          {/* Acceptable Use */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptable Use</h2>
            <p className="mb-4">
              You agree to use Somnio only for lawful purposes and in accordance with these Terms.
              You must <strong>not</strong>:
            </p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li>
                Submit dream descriptions that contain hate speech, threats, harassment, or
                content that promotes violence or discrimination against any individual or group.
              </li>
              <li>
                Submit content that is sexually explicit, obscene, or pornographic.
              </li>
              <li>
                Attempt to use the service to generate content that violates the rights of others,
                including intellectual property, privacy, or publicity rights.
              </li>
              <li>
                Use the service to scrape, crawl, or systematically extract data beyond normal
                personal use.
              </li>
              <li>
                Attempt to probe, scan, or test the vulnerability of any system or network, or
                bypass any security or authentication mechanism.
              </li>
              <li>
                Misrepresent your identity or impersonate any person or entity.
              </li>
              <li>
                Use automated means (bots, scripts) to interact with the service without prior
                written permission.
              </li>
              <li>
                Use the service in any way that could violate applicable law, including data
                protection, privacy, or consumer protection laws.
              </li>
            </ul>
            <p>
              We reserve the right to remove content, suspend, or terminate accounts that violate
              these rules, at our sole discretion, without notice.
            </p>
          </section>

          {/* AI output disclaimer */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">
              2. AI Output — Not Professional Advice
            </h2>
            <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-4 mb-4">
              <p className="text-yellow-100/90 text-sm font-medium">
                The dream interpretations, symbol analyses, and any other content generated by
                Somnio&apos;s AI are provided <strong>for self-reflection and entertainment
                purposes only</strong>. They do not constitute:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-yellow-100/80 text-sm">
                <li>Medical or psychiatric advice, diagnosis, or treatment;</li>
                <li>Psychological or therapeutic counselling;</li>
                <li>Legal advice; or</li>
                <li>Any other form of professional advice.</li>
              </ul>
            </div>
            <p>
              AI-generated content may be inaccurate, incomplete, or not applicable to your
              personal circumstances. Always seek the advice of a qualified professional for
              mental health, medical, legal, or other concerns. If you are in crisis, please
              contact emergency services or a crisis helpline.
            </p>
          </section>

          {/* User-Generated Content */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">
              3. User-Generated Content &amp; Licence
            </h2>
            <p className="mb-4">
              You retain ownership of the dream descriptions you submit (&quot;your
              content&quot;). By submitting content to Somnio, you grant us a worldwide,
              non-exclusive, royalty-free licence to:
            </p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li>Store your content in our database;</li>
              <li>Display it to you within the service;</li>
              <li>
                Transmit it to our AI processors (Anthropic, Replicate) solely for the purpose
                of generating your interpretation and image;
              </li>
              <li>
                Display it publicly if you choose to create a share link (see our{' '}
                <Link href="/privacy" className="text-purple-400 hover:text-purple-300 underline">
                  Privacy Policy
                </Link>
                ).
              </li>
            </ul>
            <p className="mb-4">
              This licence is limited to what is necessary for us to operate the service. We do
              not use your content for training AI models or for any purpose other than delivering
              the service.
            </p>
            <p>
              You represent and warrant that you own or have the necessary rights to submit your
              content, and that your content does not violate any third-party rights or applicable
              law.
            </p>
          </section>

          {/* Accounts */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">4. Accounts</h2>
            <p className="mb-3">
              You are responsible for maintaining the security of your account credentials. You
              must not share your account with others. Notify us immediately at{' '}
              <a
                href="mailto:privacy@farallone.com"
                className="text-purple-400 hover:text-purple-300 underline"
              >
                privacy@farallone.com
              </a>{' '}
              if you suspect unauthorised access.
            </p>
            <p>
              We reserve the right to suspend or permanently terminate any account that violates
              these Terms, at our sole discretion. Upon termination, your right to use the service
              ceases immediately. You may request deletion of your data as described in our{' '}
              <Link href="/privacy" className="text-purple-400 hover:text-purple-300 underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          {/* Intellectual Property */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">5. Intellectual Property</h2>
            <p className="mb-3">
              The Somnio name, logo, design, and all original software are owned by or licensed
              to us. Nothing in these Terms transfers any intellectual property rights to you,
              except the limited right to use the service as described herein.
            </p>
            <p>
              AI-generated images produced for your dream entries are provided for your personal
              use. We make no warranty as to their copyright status under applicable law, given
              the evolving legal landscape around AI-generated works. You use them at your own risk.
            </p>
          </section>

          {/* Disclaimers & Liability */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">
              6. Disclaimers &amp; Limitation of Liability
            </h2>
            <p className="mb-4 uppercase text-sm font-semibold text-gray-400">
              The service is provided &quot;as is&quot; and &quot;as available&quot; without
              warranties of any kind, express or implied, including but not limited to
              merchantability, fitness for a particular purpose, and non-infringement.
            </p>
            <p className="mb-4">
              We do not warrant that the service will be uninterrupted, error-free, or free of
              harmful components. We do not warrant the accuracy, completeness, or usefulness of
              any AI-generated content.
            </p>
            <p>
              To the maximum extent permitted by applicable law, Somnio and its operators shall
              not be liable for any indirect, incidental, special, consequential, or punitive
              damages arising from your use of or inability to use the service, even if advised
              of the possibility of such damages. Our total aggregate liability to you shall not
              exceed the greater of (a) the amount you paid us in the 12 months preceding the
              claim, or (b) USD $10.
            </p>
          </section>

          {/* Indemnification */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">7. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless Somnio and its operators from
              and against any claims, liabilities, damages, and expenses (including reasonable
              attorneys&apos; fees) arising out of your use of the service, your content, or your
              violation of these Terms.
            </p>
          </section>

          {/* Governing Law */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">8. Governing Law</h2>
            <p className="mb-3">
              These Terms are governed by the laws of the State of California, United States,
              without regard to conflict-of-law provisions. Any dispute arising from these Terms or
              your use of the service shall be resolved exclusively in the state or federal courts
              located in California, and you consent to the personal jurisdiction of those courts.
              Farallone Media LLC is the operating entity for this service.
            </p>
            <p>
              If any provision of these Terms is found to be unenforceable, the remaining
              provisions will remain in full force and effect.
            </p>
          </section>

          {/* Changes */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">9. Changes to These Terms</h2>
            <p>
              We may modify these Terms at any time. We will update the &quot;Last updated&quot;
              date and, for material changes, notify you by email or a prominent notice. Continued
              use of the service after changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          {/* Contact */}
          <section className="glass rounded-2xl p-8 border border-purple-500/20">
            <h2 className="text-2xl font-semibold text-white mb-4">10. Contact</h2>
            <p>
              Questions about these Terms? Reach us at{' '}
              <a
                href="mailto:privacy@farallone.com"
                className="text-purple-400 hover:text-purple-300 underline"
              >
                privacy@farallone.com
              </a>{' '}
              or via our{' '}
              <Link href="/contact" className="text-purple-400 hover:text-purple-300 underline">
                Contact page
              </Link>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
